import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'en' | 'or' | 'ta';

interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dictionary: Record<LanguageType, Record<string, string>> = {
  en: {
    // Nav Items
    dashboard: 'Dashboard',
    disease_register: 'Disease Register',
    gis_map: 'GIS Outbreak Map',
    report_case: 'Report Disease Case',
    disease_db: 'Disease Database',
    ai_forecast: 'AI Forecasting Hub',
    reports_hub: 'Reports Hub',
    
    // Header & Sidebar
    portal_title: 'ODISHA STATE HEALTH PORTAL',
    system_title: 'Integrated Outbreak & Containment Heuristics System (IOCHS)',
    sign_out: 'Sign Out',
    realtime_connected: 'Realtime Connected',
    realtime_offline: 'Offline / Reconnecting',
    gov_sub: 'Disease Surveillance Portal',
    gov_title: 'Govt. of Odisha',
    
    // Dashboard stats
    cases_today: 'Cases Today',
    cases_week: 'Cases This Week',
    cases_month: 'Cases This Month',
    active_outbreaks: 'Active Outbreaks',
    recovered_cases: 'Recovered Cases',
    mortalities: 'Mortalities',
    regional_alerts: 'Regional Alert Levels',
    live_containment: 'Live Containment Bulletins',
    disease_progression: 'Disease Progression Trend',
    risk_breakdown: 'Risk Level Breakdown',
    click_bed_info: 'Click on any district above to check facility beds.',
    
    // Case Form
    diagnose_case_title: 'Infectious Disease Case Report',
    diagnose_case_sub: 'Add active surveillance case updates to real-time maps.',
    patient_details: 'Patient Details',
    patient_id: 'Patient ID (Auditable)',
    daily_count: 'Daily Patient Count',
    age: 'Age',
    representative_age: 'Representative Age',
    gender_distribution: 'Gender Distribution',
    diagnosed_disease: 'Diagnosed Disease / Pathogen',
    severity_assessment: 'Severity Assessment',
    focus_pathogen: 'Configure Pathogen',
    immunization_status: 'Immunization status (Vaccinated)',
    patient_vaccinated: 'Patient is vaccinated for this disease',
    gis_coordinates: 'GIS Coordinates Mapping',
    auto_gps: 'Auto-Locate GPS',
    district: 'District',
    block: 'Block',
    gram_panchayat: 'Gram Panchayat',
    village_ward: 'Village / Ward',
    diagnosis_status: 'Diagnosis Status',
    clinical_isolation: 'Clinical Isolation Status',
    hospital_name: 'Medical Center / Hospital Name',
    symptom_notes: 'Symptoms Notes',
    travel_history: 'Travel & Contacts History',
    submit_report: 'Submit Case Report',
    
    // Options
    male_only: 'Male Only',
    female_only: 'Female Only',
    other: 'Other',
    mixed_genders: 'Mixed Genders (Distributed)',
    low_risk: 'Low Risk',
    medium_alert: 'Medium Alert',
    high_outbreak: 'High Outbreak (Notify)',
    suspected: 'Suspected',
    confirmed: 'Confirmed Diagnosis',
    recovered: 'Recovered',
    death: 'Mortality (Death)',
    home_quarantine: 'Home Quarantine',
    isolation: 'PHC Isolation Ward',
    hospitalized: 'Hospitalized (Beds)',

    // Disease DB Headers
    disease_db_title: 'Disease Registries Database',
    disease_db_sub: 'Government approved pathogens list and containment thresholds.',
    configure_pathogen: 'Configure Pathogen',
    configure_pathogen_title: 'Configure Custom Pathogen Thresholds',
    pathogen_name: 'Pathogen Name',
    category: 'Category',
    alert_threshold: 'Weekly Alert Trigger Threshold',
    symptoms_desc: 'Diagnostic Symptoms Description',
    treatment_checklist: 'First-line Treatment Checklist',
    containment_directives: 'AI Containment Zone Directives',
    cancel: 'Cancel',
    configure_registry: 'Configure Registry',
    certified_text: 'Certified under State Health Act',
    limit_text: 'Limit',
    cases_wk: 'cases/wk',
    symptoms_lbl: 'Symptoms',

    // Specific Disease Mock Content
    "Dengue": "Dengue",
    "Malaria": "Malaria",
    "Cholera": "Cholera",
    "Vector-borne": "Vector-borne (Mosquito/Ticks)",
    "Water-borne": "Water-borne (Fecal-Oral)",
    "Airborne": "Airborne (Droplets/Aerosols)",
    "Direct Contact": "Direct Contact / Zoonotic",
    "Focal insecticide fogging, standing water cleaning": "Focal insecticide fogging, standing water cleaning",
    "LLIN mosquito net distribution": "LLIN mosquito net distribution",
    "Chlorination of water sources, hygiene audits": "Chlorination of water sources, hygiene audits",
    "Paracetamol, ORS": "Paracetamol, ORS",
    "ACT, Chloroquine": "ACT, Chloroquine",
    "Doxycycline, ORS": "Doxycycline, ORS",
    "High fever, respiratory complications, joint pain.": "High fever, respiratory complications, joint pain.",

    // AI Forecast Page
    ai_containment_forecasts: "AI Containment & Outbreak Forecasts",
    heuristics_engine_sub: "Heuristics engine computing spatial DBSCAN clusters and 7-day caseload growth trends.",
    predictive_growth_modeling: "Predictive Growth Modeling",
    trend_calculations_sub: "7-Day trend calculations for active conditions",
    active_cases: "Active Cases",
    forecast_7d: "Forecast (7 Days)",
    growth_slope: "Growth Slope",
    risk_score: "Risk Score",
    ai_action_directives: "AI Action Directives for",
    confidence_index_text: "Confidence Index is derived from historical district reporting frequency.",
    density_hotspots: "Density Hotspots (DBSCAN)",
    identified_coordinates: "Identified coordinates clusters in last 14 days",
    no_clusters_detected: "No cluster outbreaks detected.",
    registered_surveillance_hub: "Registered Case Surveillance Hub (Forecasting Inputs)",
    active_sub_registry: "Active case reporting submitted via the State Disease Registry portal.",
    all_years: "All Years",
    all_months: "All Months",
    primary_pathogen: "Primary Pathogen",
    cases_in_cluster: "Cases In Cluster",
    location_centroid: "Location Centroid / Radius",
    reported: "reported",
    cluster_centroid: "Cluster Centroid",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    december: "December",
    enforce_active_surveillance_prefix: "Enforce active surveillance within a 2km radius of reported cases in",
    patient_name_id: 'Patient Name & ID',
    disease_pathogen: 'Disease Pathogen',
    place_district: 'Place / District',
    affected_persons_count: 'Affected Persons Count',
    registration_date: 'Registration Date',
    no_registered_cases_matching: 'No registered cases found matching selected time filters.',
    increasing: 'Increasing',
    stable: 'Stable / Down'
  },
  or: {
    // Nav Items
    dashboard: '\u0b21\u0b4d\u0b5f\u0b3e\u0b38\u0b2c\u0b4b\u0b30\u0b4d\u0b21',
    disease_register: '\u0b30\u0b4b\u0b17 \u0b2a\u0b1e\u0b4d\u0b1c\u0b3f\u0b15\u0b30\u0b23',
    gis_map: 'GIS à¬ªà­à¬°à¬¾à¬¦à­à¬°à­à¬­à¬¾à¬¬ à¬®à¬¾à¬¨à¬šà¬¿à¬¤à­à¬°',
    report_case: 'à¬°à­‹à¬— à¬®à¬¾à¬®à¬²à¬¾ à¬°à¬¿à¬ªà­‹à¬°à­à¬Ÿ',
    disease_db: 'à¬°à­‹à¬— à¬¡à¬¾à¬Ÿà¬¾à¬¬à­‡à¬¸à­',
    ai_forecast: 'AI à¬ªà­‚à¬°à­à¬¬à¬¾à¬¨à­à¬®à¬¾à¬¨ à¬¹à¬¬à­',
    reports_hub: 'à¬°à¬¿à¬ªà­‹à¬°à­à¬Ÿ à¬¹à¬¬à­',
    
    // Header & Sidebar
    portal_title: 'à¬“à¬¡à¬¼à¬¿à¬¶à¬¾ à¬°à¬¾à¬œà­à­Ÿ à¬¸à­à­±à¬¾à¬¸à­à¬¥à­à­Ÿ à¬ªà­‹à¬°à­à¬Ÿà¬¾à¬²à­',
    system_title: 'à¬¸à¬®à¬¨à­à­±à¬¿à¬¤ à¬ªà­à¬°à¬¾à¬¦à­à¬°à­à¬­à¬¾à¬¬ à¬à¬¬à¬‚ à¬¨à¬¿à­Ÿà¬¨à­à¬¤à­à¬°à¬£ à¬¹à­à­Ÿà­à¬°à¬¿à¬·à­à¬Ÿà¬¿à¬•à­ à¬¸à¬¿à¬·à­à¬Ÿà¬®à­ (IOCHS)',
    sign_out: 'à¬¸à¬¾à¬‡à¬¨à­ à¬†à¬‰à¬Ÿà­',
    realtime_connected: 'à¬°à¬¿à¬…à¬²à­-à¬Ÿà¬¾à¬‡à¬®à­ à¬¸à¬‚à¬¯à­à¬•à­à¬¤',
    realtime_offline: 'à¬…à¬«à¬²à¬¾à¬‡à¬¨à­ / à¬¸à¬‚à¬¯à­‹à¬— à¬¹à­‡à¬‰à¬›à¬¿',
    gov_sub: 'à¬°à­‹à¬— à¬¨à­€à¬°à¬¿à¬•à­à¬·à¬£ à¬ªà­‹à¬°à­à¬Ÿà¬¾à¬²à­',
    gov_title: 'à¬“à¬¡à¬¼à¬¿à¬¶à¬¾ à¬¸à¬°à¬•à¬¾à¬°',
    
    // Dashboard stats
    cases_today: 'à¬†à¬œà¬¿à¬° à¬®à¬¾à¬®à¬²à¬¾',
    cases_week: 'à¬à¬¹à¬¿ à¬¸à¬ªà­à¬¤à¬¾à¬¹à¬° à¬®à¬¾à¬®à¬²à¬¾',
    cases_month: 'à¬à¬¹à¬¿ à¬®à¬¾à¬¸à¬° à¬®à¬¾à¬®à¬²à¬¾',
    active_outbreaks: 'à¬¸à¬•à­à¬°à¬¿à­Ÿ à¬ªà­à¬°à¬¾à¬¦à­à¬°à­à¬­à¬¾à¬¬',
    recovered_cases: 'à¬¸à­à¬¸à­à¬¥ à¬¹à­‹à¬‡à¬¥à¬¿à¬¬à¬¾ à¬®à¬¾à¬®à¬²à¬¾',
    mortalities: 'à¬®à­ƒà¬¤à­à­Ÿà­à¬¸à¬‚à¬–à­à­Ÿà¬¾',
    regional_alerts: 'à¬†à¬žà­à¬šà¬³à¬¿à¬• à¬¸à¬¤à¬°à­à¬•à¬¤à¬¾ à¬¸à­à¬¤à¬°',
    live_containment: 'à¬²à¬¾à¬‡à¬­à­ à¬•à¬£à­à¬Ÿà­‡à¬¨à¬®à­‡à¬£à­à¬Ÿ à¬¬à­à¬²à­‡à¬Ÿà¬¿à¬¨à­',
    disease_progression: 'à¬°à­‹à¬—à¬° à¬…à¬—à­à¬°à¬—à¬¤à¬¿ à¬§à¬¾à¬°à¬¾',
    risk_breakdown: 'à¬à­à¬™à­à¬•à¬¿ à¬¸à­à¬¤à¬° à¬¬à¬¿à¬­à¬¾à¬œà¬¨',
    click_bed_info: 'à¬¶à¬¯à­à­Ÿà¬¾ à¬¸à¬‚à¬–à­à­Ÿà¬¾ à¬¯à¬¾à¬žà­à¬š à¬•à¬°à¬¿à¬¬à¬¾ à¬ªà¬¾à¬‡à¬ à¬¯à­‡à¬•à­Œà¬£à¬¸à¬¿ à¬œà¬¿à¬²à­à¬²à¬¾ à¬‰à¬ªà¬°à­‡ à¬•à­à¬²à¬¿à¬•à­ à¬•à¬°à¬¨à­à¬¤à­ |',
    
    // Case Form
    diagnose_case_title: 'à¬¸à¬‚à¬•à­à¬°à¬¾à¬®à¬• à¬°à­‹à¬— à¬®à¬¾à¬®à¬²à¬¾ à¬°à¬¿à¬ªà­‹à¬°à­à¬Ÿ',
    diagnose_case_sub: 'à¬°à¬¿à¬…à¬²à­-à¬Ÿà¬¾à¬‡à¬®à­ à¬®à¬¾à¬¨à¬šà¬¿à¬¤à­à¬°à¬°à­‡ à¬¸à¬•à­à¬°à¬¿à­Ÿ à¬¨à­€à¬°à¬¿à¬•à­à¬·à¬£ à¬®à¬¾à¬®à¬²à¬¾ à¬…à¬ªà¬¡à­‡à¬Ÿà­ à¬¯à­‹à¬¡à¬¨à­à¬¤à­ |',
    patient_details: 'à¬°à­‹à¬—à­€à¬° à¬¬à¬¿à¬¬à¬°à¬£à­€',
    patient_id: 'à¬°à­‹à¬—à­€ à¬†à¬‡à¬¡à¬¿ (à¬…à¬¡à¬¿à¬Ÿà­‡à¬¬à¬²à­)',
    daily_count: 'à¬¦à­ˆà¬¨à¬¿à¬• à¬°à­‹à¬—à­€ à¬¸à¬‚à¬–à­à­Ÿà¬¾',
    age: 'à¬¬à­Ÿà¬¸',
    representative_age: 'à¬ªà­à¬°à¬¤à¬¿à¬¨à¬¿à¬§à¬¿ à¬¬à­Ÿà¬¸',
    gender_distribution: 'à¬²à¬¿à¬™à­à¬— à¬¬à¬¿à¬¤à¬°à¬£',
    diagnosed_disease: 'à¬šà¬¿à¬¹à­à¬¨à¬Ÿ à¬°à­‹à¬— / à¬œà­€à¬¬à¬¾à¬£à­',
    severity_assessment: 'à¬—à­à¬°à­à¬¤à¬° à¬†à¬•à¬³à¬¨',
    focus_pathogen: 'à¬°à­‹à¬— à¬•à¬¨à¬«à¬¿à¬—à¬°à­ à¬•à¬°à¬¨à­à¬¤à­',
    immunization_status: 'à¬Ÿà¬¿à¬•à¬¾à¬•à¬°à¬£ à¬¸à­à¬¥à¬¿à¬¤à¬¿ (à¬Ÿà¬¿à¬•à¬¾ à¬¨à­‡à¬‡à¬¥à¬¿à¬¬à¬¾)',
    patient_vaccinated: 'à¬°à­‹à¬—à­€ à¬à¬¹à¬¿ à¬°à­‹à¬— à¬ªà¬¾à¬‡à¬ à¬Ÿà¬¿à¬•à¬¾ à¬¨à­‡à¬‡à¬›à¬¨à­à¬¤à¬¿',
    gis_coordinates: 'GIS à¬¸à­à¬¥à¬¾à¬¨à¬¾à¬™à­à¬• à¬®à¬¾à¬¨à¬šà¬¿à¬¤à­à¬°à¬£',
    auto_gps: 'à¬¸à­à­±à­Ÿà¬‚à¬šà¬¾à¬³à¬¿à¬¤ GPS à¬…à¬¬à¬¸à­à¬¥à¬¾à¬¨',
    district: 'à¬œà¬¿à¬²à­à¬²à¬¾',
    block: 'à¬¬à­à¬²à¬•',
    gram_panchayat: 'à¬—à­à¬°à¬¾à¬® à¬ªà¬žà­à¬šà¬¾à­Ÿà¬¤',
    village_ward: 'à¬—à­à¬°à¬¾à¬® / à­±à¬¾à¬°à­à¬¡',
    diagnosis_status: 'à¬¨à¬¿à¬¦à¬¾à¬¨ à¬¸à­à¬¥à¬¿à¬¤à¬¿',
    clinical_isolation: 'à¬•à­à¬²à¬¿à¬¨à¬¿à¬•à¬¾à¬²à­ à¬ªà­ƒà¬¥à¬•à­€à¬•à¬°à¬£ à¬¸à­à¬¥à¬¿à¬¤à¬¿',
    hospital_name: 'à¬¡à¬¾à¬•à­à¬¤à¬°à¬–à¬¾à¬¨à¬¾à¬° à¬¨à¬¾à¬®',
    symptom_notes: 'à¬²à¬•à­à¬·à¬£ à¬¨à­‹à¬Ÿà­',
    travel_history: 'à¬¯à¬¾à¬¤à­à¬°à¬¾ à¬à¬¬à¬‚ à¬¸à¬®à­à¬ªà¬°à­à¬• à¬‡à¬¤à¬¿à¬¹à¬¾à¬¸',
    submit_report: 'à¬®à¬¾à¬®à¬²à¬¾ à¬°à¬¿à¬ªà­‹à¬°à­à¬Ÿ à¬¦à¬¾à¬–à¬² à¬•à¬°à¬¨à­à¬¤à­',
    
    // Options
    male_only: 'à¬•à­‡à¬¬à¬³ à¬ªà­à¬°à­à¬·',
    female_only: 'à¬•à­‡à¬¬à¬³ à¬®à¬¹à¬¿à¬³à¬¾',
    other: 'à¬…à¬¨à­à­Ÿà¬¾à¬¨à­à­Ÿ',
    mixed_genders: 'à¬®à¬¿à¬¶à­à¬°à¬¿à¬¤ à¬²à¬¿à¬™à­à¬— (à¬¬à¬¿à¬¤à¬°à¬¿à¬¤)',
    low_risk: 'à¬•à¬®à­ à¬¬à¬¿à¬ªà¬¦',
    medium_alert: 'à¬®à¬§à­à­Ÿà¬® à¬¸à¬¤à¬°à­à¬•à¬¤à¬¾',
    high_outbreak: 'à¬‰à¬šà­à¬š à¬ªà­à¬°à¬¾à¬¦à­à¬°à­à¬­à¬¾à¬¬ (à¬¸à­‚à¬šà¬¨à¬¾ à¬¦à¬¿à¬…à¬¨à­à¬¤à­)',
    suspected: 'à¬¸à¬¨à­à¬¦à­‡à¬¹à¬œà¬¨à¬•',
    confirmed: 'à¬¨à¬¿à¬¶à­à¬šà¬¿à¬¤ à¬¨à¬¿à¬¦à¬¾à¬¨',
    recovered: 'à¬¸à­à¬¸à­à¬¥ à¬¹à­‹à¬‡à¬›à¬¿',
    death: 'à¬®à­ƒà¬¤à­à­Ÿà­',
    home_quarantine: 'à¬¹à­‹à¬®à­ à¬•à­à­±à¬¾à¬°à­‡à¬£à­à¬Ÿà¬¾à¬‡à¬¨à­',
    isolation: 'PHC à¬ªà­ƒà¬¥à¬•à­€à¬•à¬°à¬£ à­±à¬¾à¬°à­à¬¡',
    hospitalized: 'à¬¡à¬¾à¬•à­à¬¤à¬°à¬–à¬¾à¬¨à¬¾à¬°à­‡ à¬­à¬°à­à¬¤à­à¬¤à¬¿',

    // Disease DB Headers
    disease_db_title: 'à¬°à­‹à¬— à¬ªà¬žà­à¬œà¬¿à¬•à¬°à¬£ à¬¡à¬¾à¬Ÿà¬¾à¬¬à­‡à¬¸à­',
    disease_db_sub: 'à¬¸à¬°à¬•à¬¾à¬°à­€ à¬…à¬¨à­à¬®à­‹à¬¦à¬¿à¬¤ à¬°à­‹à¬— à¬à¬¬à¬‚ à¬¨à¬¿à­Ÿà¬¨à­à¬¤à­à¬°à¬£ à¬¸à­€à¬®à¬¾ |',
    configure_pathogen: 'à¬°à­‹à¬— à¬•à¬¨à¬«à¬¿à¬—à¬°à­ à¬•à¬°à¬¨à­à¬¤à­',
    configure_pathogen_title: 'à¬•à¬·à­à¬Ÿà¬®à­ à¬°à­‹à¬— à¬¨à¬¿à­Ÿà¬¨à­à¬¤à­à¬°à¬£ à¬¸à­€à¬®à¬¾ à¬•à¬¨à¬«à¬¿à¬—à¬°à­ à¬•à¬°à¬¨à­à¬¤à­',
    pathogen_name: 'à¬°à­‹à¬—à¬° à¬¨à¬¾à¬®',
    category: 'à¬¬à¬¿à¬­à¬¾à¬—',
    alert_threshold: 'à¬¸à¬¾à¬ªà­à¬¤à¬¾à¬¹à¬¿à¬• à¬¸à¬¤à¬°à­à¬•à¬¤à¬¾ à¬¸à­€à¬®à¬¾',
    symptoms_desc: 'à¬²à¬•à­à¬·à¬£ à¬¬à¬°à­à¬£à­à¬£à¬¨à¬¾',
    treatment_checklist: 'à¬ªà­à¬°à¬¾à¬¥à¬®à¬¿à¬• à¬šà¬¿à¬•à¬¿à¬¤à­à¬¸à¬¾ à¬¯à¬¾à¬žà­à¬š à¬¤à¬¾à¬²à¬¿à¬•à¬¾',
    containment_directives: 'AI à¬¨à¬¿à­Ÿà¬¨à­à¬¤à­à¬°à¬£ à¬œà­‹à¬¨à­ à¬¨à¬¿à¬°à­à¬¦à­à¬¦à­‡à¬¶à¬¾à¬¬à¬³à­€',
    cancel: 'à¬¬à¬¾à¬¤à¬¿à¬²à­',
    configure_registry: 'à¬ªà¬žà­à¬œà¬¿à¬•à¬°à¬£ à¬•à¬¨à¬«à¬¿à¬—à¬°à­ à¬•à¬°à¬¨à­à¬¤à­',
    certified_text: 'à¬°à¬¾à¬œà­à­Ÿ à¬¸à­à­±à¬¾à¬¸à­à¬¥à­à­Ÿ à¬…à¬§à¬¿à¬¨à¬¿à­Ÿà¬® à¬…à¬§à­€à¬¨à¬°à­‡ à¬ªà­à¬°à¬®à¬¾à¬£à¬¿à¬¤',
    limit_text: 'à¬¸à­€à¬®à¬¾',
    cases_wk: 'à¬®à¬¾à¬®à¬²à¬¾ / à¬¸à¬ªà­à¬¤à¬¾à¬¹',
    symptoms_lbl: 'à¬²à¬•à­à¬·à¬£',

    // Specific Disease Mock Content
    "Dengue": "à¬¡à­‡à¬™à­à¬—à­",
    "Malaria": "à¬®à­à­Ÿà¬¾à¬²à­‡à¬°à¬¿à¬†",
    "Cholera": "à¬•à¬²à­‡à¬°à¬¾",
    "Vector-borne": "à¬¬à¬¾à¬¹à¬•-à¬¬à¬¾à¬¹à¬¿à¬¤",
    "Water-borne": "à¬œà¬³-à¬¬à¬¾à¬¹à¬¿à¬¤",
    "Airborne": "à¬¬à¬¾à­Ÿà­-à¬¬à¬¾à¬¹à¬¿à¬¤",
    "Direct Contact": "à¬¸à¬¿à¬§à¬¾à¬¸à¬³à¬– à¬¸à¬®à­à¬ªà¬°à­à¬•",
    "Focal insecticide fogging, standing water cleaning": "à¬•à­€à¬Ÿà¬¨à¬¾à¬¶à¬• à¬¸à­à¬ªà­à¬°à­‡ à¬•à¬°à¬¿à¬¬à¬¾, à¬œà¬®à¬¾ à¬¹à­‹à¬‡à¬¥à¬¿à¬¬à¬¾ à¬œà¬³ à¬¸à¬«à¬¾ à¬•à¬°à¬¿à¬¬à¬¾",
    "LLIN mosquito net distribution": "LLIN à¬®à¬¶à¬¾à¬°à­€ à¬¬à¬¿à¬¤à¬°à¬£",
    "Chlorination of water sources, hygiene audits": "à¬œà¬³ à¬‰à¬¤à­à¬¸à¬—à­à¬¡à¬¼à¬¿à¬•à¬° à¬•à­à¬²à­‹à¬°à¬¿à¬¨à­‡à¬¸à¬¨à­, à¬¸à­à­±à¬šà­à¬›à¬¤à¬¾ à¬…à¬¡à¬¿à¬Ÿà­",
    "Paracetamol, ORS": "à¬ªà¬¾à¬°à¬¾à¬¸à¬¿à¬Ÿà¬¾à¬®à­‹à¬²à­, ORS",
    "ACT, Chloroquine": "ACT, à¬•à­à¬²à­‹à¬°à­‹à¬•à­à¬‡à¬¨à­",
    "Doxycycline, ORS": "à¬¡à¬•à­à¬¸à¬¿à¬¸à¬¾à¬‡à¬•à­à¬²à¬¿à¬¨à­, ORS",
    "High fever, respiratory complications, joint pain.": "à¬‰à¬šà­à¬š à¬œà­à­±\u200c°, à¬¶à­à­±à¬¾à¬¸à¬•à­à¬°à¬¿à­Ÿà¬¾ à¬œà¬Ÿà¬¿à¬³à¬¤à¬¾, à¬—à¬£à­à¬ à¬¿ à¬¯à¬¨à­à¬¤à­à¬°à¬£à¬¾ |",

    // AI Forecast Page
    ai_containment_forecasts: "AI ନିୟନ୍ତ୍ରଣ ଏବଂ ପ୍ରାଦୁର୍ଭାବ ପୂର୍ବାନୁମାନ",
    heuristics_engine_sub: "ସ୍ପାସିଆଲ୍ DBSCAN କ୍ଲଷ୍ଟର୍ ଏବ้ง ୭ ଦିନିଆ ମାମଲା ବୃଦ୍ଧି ପୂର୍ବାନୁମାନ କରୁଥିବା ଇଞ୍ଜିନ୍ |",
    predictive_growth_modeling: "ପୂର୍ବାନୁମାନ ବୃଦ୍ଧି ମଡେଲିଂ",
    trend_calculations_sub: "ସକ୍ରିୟ ସ୍ଥିତି ପାଇଁ ୭ ଦିନିଆ ଟ୍ରେଣ୍ଡ୍ ହିସାବ",
    active_cases: "ସକ୍ରିୟ ମାମଲା",
    forecast_7d: "ପୂର୍ବାନୁମାନ (୭ ଦିନ)",
    growth_slope: "ବୃଦ୍ଧି ହାର",
    risk_score: "ବିପଦ ସ୍କୋର",
    ai_action_directives: "AI କାର୍ଯ୍ୟ ନିର୍ଦ୍ଦେଶାବଳୀ - ",
    confidence_index_text: "ବିଶ୍ୱାସ ସୂଚକାଙ୍କ ଜିଲ୍ଲାର ଐତିହାସିକ ରିପୋର୍ଟ ଉପରେ ଆଧାରିତ |",
    density_hotspots: "ଘନତା ହଟସ୍ପଟ୍ (DBSCAN)",
    identified_coordinates: "ଶେଷ ୧୪ ଦିନରେ ଚିହ୍ନଟ ହୋଇଥିବା କ୍லଷ୍ଟର",
    no_clusters_detected: "କୌଣସି କ୍ଲଷ୍ଟର ଚିହ୍ନଟ ହୋଇନାହିଁ |",
    registered_surveillance_hub: "ପଞ୍ଜୀକୃତ ମାମଲା ନୀରିକ୍ଷଣ କେନ୍ଦ୍ର",
    active_sub_registry: "ରାଜ୍ୟ ରୋଗ ପଞ୍ଜିକା ଦ୍ୱାରା ଦାଖଲ ହୋଇଥିବା ସକ୍ରିୟ ମାମଲା |",
    all_years: "ସମସ୍ତ ବର୍ଷ",
    all_months: "ସମସ୍ତ ମାସ",
    primary_pathogen: "ପ୍ରାଥମିକ ରୋଗକାରକ",
    cases_in_cluster: "କ୍ଲଷ୍ଟରରେ ଥିବା ମାମଲା",
    location_centroid: "ଅବସ୍ଥିତି କେନ୍ଦ୍ର / ବ୍ୟାସାର୍ଦ୍ଧ",
    reported: "ରିପୋର୍ଟ ହୋଇଛି",
    cluster_centroid: "କ୍ଲଷ୍ଟର୍ କେନ୍ଦ୍ର",
    january: "ଜାନୁଆରୀ",
    february: "ଫେବୃଆରୀ",
    march: "ମାର୍ଚ୍ଚ",
    april: "ଅପ୍ରେଲ୍",
    may: "ମଇ",
    june: "ଜୁନ୍",
    july: "ଜୁଲାଇ",
    august: "ଅଗଷ୍ଟ",
    september: "ସେପ୍ଟେମ୍ବର",
    october: "ଅକ୍ଟୋବର",
    november: "ନଭେମ୍ବର",
    december: "ଡିସେମ୍ବର",
    enforce_active_surveillance_prefix: "ଚିହ୍ନଟ ମାମଲାଗୁଡ଼ିକର ୨ କିଲୋମିଟର ପରିସର ମଧ୍ୟରେ ସକ୍ରିୟ ନୀରିକ୍ଷଣ ଲାଗୁ କରନ୍ତୁ -",

    // Directives
    "Eliminate standing water containers and conduct focal insecticide fogging.": "ଜମା ହୋଇଥିବା ପାଣି ପାତ୍ରଗୁଡ଼ିକୁ ସଫା କରନ୍ତୁ ଏବଂ କୀଟନାଶକ ସ୍ପ୍ରେ କରନ୍ତୁ |",
    "Distribute LLIN mosquito bed nets to households in affected blocks.": "ପ୍ରଭାବିତ ବ୍ଲକଗୁଡ଼ିକରେ ଲୋକମାନଙ୍କୁ LLIN ମଶାରୀ ବିତରଣ କରନ୍ତୁ |",
    "Ensure local primary health centers have adequate stocks of paracetamol and diagnostic kits.": "ସ୍ଥାନୀୟ ପ୍ରାଥମିକ ସ୍ୱାସ୍ଥ୍ୟ କେନ୍ଦ୍ରଗୁଡ଼ିକରେ ପାରାସିଟାମୋଲ ଏବଂ ରୋଗ ଚିହ୍ନଟ କିଟ୍ ମହଜୁଦ ରଖନ୍ତୁ |",
    "Conduct Indoor Residual Spraying (IRS) in households within a 2km radius.": "୨ କିଲୋମିଟର ପରିସର ମଧ୍ୟରେ ଥିବା ଘରଗୁଡ଼ିକରେ ଇନଡୋର ସ୍ପ୍ରେ (IRS) କରନ୍ତୁ |",
    "Distribute LLIN mosquito nets and run community vector awareness campaigns.": "LLIN ମଶାରୀ ବିତରଣ କରନ୍ତୁ ଏବଂ ସଚେତନତା ସୃଷ୍ଟି କରନ୍ତୁ |",
    "Stock local health facilities with ACT (Artesunate-Sulfadoxine-Pyrimethamine) therapy.": "ସ୍ଥାନୀୟ ସ୍ୱାସ୍ଥ୍ୟ କେନ୍ଦ୍ରଗୁଡ଼ିକରେ ACT ଔଷଧ ମହଜୁଦ ରଖନ୍ତୁ |",
    "Establish emergency water purification points and distribute halogen tablets.": "ଜରୁରୀକାଳୀନ ଜଳ ବିଶୋଧନ କେନ୍ଦ୍ର ସ୍ଥାପନ କରନ୍ତୁ ଏବଂ ହାଲୋଜେନ ବଟିକା ବିତରଣ କରନ୍ତୁ |",
    "Enforce super-chlorination of local drinking water wells and municipal reservoirs.": "ପାନୀୟ ଜଳ ଉତ୍ସ ଏବଂ ଜଳାଶୟଗୁଡ଼ିକର ସୁପର-କ୍ଲୋରିନେସନ କରନ୍ତୁ |",
    "Deploy quarantine isolation units and stock facilities with Doxycycline and ORS.": "କ୍ୱାରେଣ୍ଟାଇନ ଆଇସୋଲେସନ ୟୁନିଟ୍ ପ୍ରସ୍ତୁତ ରଖନ୍ତୁ ଏବଂ ଔଷଧ (Doxycycline, ORS) ମହଜୁଦ ରଖନ୍ତୁ |",
    "Mandate face masks in public and establish immediate contact tracing for the patient ID.": "ସର୍ବସାଧାରଣ ସ୍ଥାନରେ ମାସ୍କ ବାଧ୍ୟତାମୂଳକ କରନ୍ତୁ ଏବଂ କଣ୍ଟାକ୍ଟ ଟ୍ରେସିଂ କରନ୍ତୁ |",
    "Enforce localized containment quarantine zones around the active residences.": "ସକ୍ରିୟ ରୋଗୀଙ୍କ ବାସଭବନ ଚାରିପାଖରେ କଣ୍ଟେନମେଣ୍ଟ ଜୋନ୍ ଲାଗୁ କରନ୍ତୁ |",
    "Deploy ASHA workers for daily door-to-door temperature audits and symptom logging.": "ଦୈନିକ ଦ୍ୱାରକୁ ଦ୍ୱାର ସର୍ଭେ ପାଇଁ ଆଶା କର୍ମୀଙ୍କୁ ନିୟୋଜିତ କରନ୍ତୁ |",
    "Enforce chlorination of local community drinking water wells.": "ସ୍ଥାନୀୟ ପାନୀୟ ଜଳ କୂଅଗୁଡ଼ିକର କ୍ଲୋରିନେସନ ବାଧ୍ୟତାମୂଳକ କରନ୍ତୁ |",
    "Conduct food safety sanitation audits at public food stalls and markets.": "ସର୍ବସାଧାରଣ ଖାଦ୍ୟ ଷ୍ଟଲ ଏବଂ ବଜାରଗୁଡ଼ିକର ସ୍ୱଚ୍ଛତା ଯାଞ୍ଚ କରନ୍ତୁ |",
    "Ensure local PHCs have adequate stocks of Ceftriaxone and Azithromycin.": "ସ୍ଥାନୀୟ PHC ଗୁଡ଼ିକରେ ସେଫଟ୍ରିଆକ୍ସୋନ ଏବଂ ଆଜିଥ୍ରୋମାଇସିନ ମହଜୁଦ ରଖନ୍ତୁ |",
    "Standard surveillance active. No high-risk outbreak triggers detected.": "ସାଧାରଣ ସର୍ଭେଲନ୍ସ ସକ୍ରିୟ | କୌଣସି ବିପଦ ସଙ୍କେତ ମିଳିନାହିଁ |",
    "Monitor local ASHA health logs for abnormal spike indicators.": "ଅସ୍ୱାଭାବିକ ଲକ୍ଷଣ ଉପରେ ନଜର ରଖିବା ପାଇଁ ଆଶା କର୍ମୀଙ୍କ ଲଗ୍ ଯାଞ୍ଚ କରନ୍ତୁ |",
    "Enforce active surveillance within a 2km radius of positive cases.": "ସକ୍ରିୟ ରୋଗୀ ମିଳିଥିବା ସ୍ଥାନର ୨ କିଲୋମିଟର ପରିସର ମଧ୍ୟରେ ସକ୍ରିୟ ନୀରିକ୍ଷଣ ଲାଗୁ କରନ୍ତୁ |",
    "Deploy ASHA workers for daily door-to-door temperature and symptom audits.": "ଦୈନିକ ସର୍ଭେ ପାଇଁ ଆଶା କର୍ମୀଙ୍କୁ ନିୟୋଜିତ କରନ୍ତୁ |",
    "Ensure local PHCs have adequate stocks of Dengue diagnostic kits.": "ସ୍ଥାନୀୟ PHC ଗୁଡ଼ିକରେ ଡେଙ୍ଗୁ ଚିହ୍ନଟ କିଟ୍ ମହଜୁଦ ରଖନ୍ତୁ |",
    "Enforce active surveillance within a 2km radius.": "୨ କିଲୋମିଟର ପରିସର ମଧ୍ୟରେ ସକ୍ରିୟ ନୀରିକ୍ଷଣ ଲାଗୁ କରନ୍ତୁ |",
    "Perform targeted water chlorination and bleach distribution.": "ଜଳ ବିଶୋଧନ ଏବଂ ବ୍ଲିଚିଂ ପାଉଡର ବିତରଣ କରନ୍ତୁ |",
    "Ensure SCB medical college has stocked ORS sachets.": "SCB ମେଡିକାଲ କଲେଜରେ ORS ମହଜୁଦ ରଖିବା ସୁନିଶ୍ଚିତ କରନ୍ତୁ |",
    "ASHA workers to distribute mosquito nets in Hinjilicut.": "ହିଞ୍ଜିଳିକାଟୁରେ ଆଶା କର୍ମୀଙ୍କ ଦ୍ୱାରା ମଶାରୀ ବିତରଣ କରନ୍ତୁ |",
    "Conduct indoor residual spraying.": "ଘର ଭିତରେ କୀଟନାଶକ ସ୍ପ୍ରେ କରନ୍ତୁ |",
    "Monitor local ASHA health logs.": "ଆଶା କର୍ମୀଙ୍କ ଲଗ୍ ଯାଞ୍ଚ କରନ୍ତୁ |",
    patient_name_id: 'ରୋଗୀଙ୍କ ନାମ ଏବଂ ଆଇଡି',
    disease_pathogen: 'ରୋଗ ଜୀବାଣୁ',
    place_district: 'ସ୍ଥାନ / ଜିଲ୍ଲା',
    affected_persons_count: 'ଆକ୍ରାନ୍ତଙ୍କ ସଂଖ୍ୟା',
    registration_date: 'ପଞ୍ଜୀକରଣ ତାରିଖ',
    no_registered_cases_matching: 'କୌଣସି ପଞ୍ଜୀକୃତ ମାମଲା ମିଳିଲା ନାହିଁ |',
    increasing: 'ବୃଦ୍ଧି ପାଉଛି',
    stable: 'ସ୍ଥିର'
  },
  ta: {
    // Nav Items
    dashboard: '\u0b9f\u0bbe\u0bb7\u0bcd\u0baa\u0bcb\u0bb0\u0bcd\u0b9f\u0bc1',
    disease_register: '\u0ba8\u0bcb\u0baf\u0bcd \u0baa\u0ba4\u0bbf\u0bb5\u0bc7\u0b9f\u0bc1',
    gis_map: 'ஜிஐஎஸ் பரவல் வரைபடம்',
    report_case: 'நோய் பாதிப்பை சமர்ப்பிக்கவும்',
    disease_db: 'நோய் தரவுத்தளம்',
    ai_forecast: 'AI கணிப்பு மையம்',
    reports_hub: 'அறிக்கை மையம்',
    
    // Header & Sidebar
    portal_title: 'ஒடிசா மாநில சுகாதார போர்டல்',
    system_title: 'ஒருங்கிணைந்த நோய் பரவல் மற்றும் கட்டுப்பாட்டு விதிமுறை அமைப்பு (IOCHS)',
    sign_out: 'வெளியேறு',
    realtime_connected: 'நிகழ்நேர இணைப்பு',
    realtime_offline: 'ஆஃப்லைன் / மீண்டும் இணைக்கிறது',
    gov_sub: 'நோய் கண்காணிப்பு போர்டல்',
    gov_title: 'ஒடிசா அரசு',
    
    // Dashboard stats
    cases_today: 'இன்றைய பாதிப்புகள்',
    cases_week: 'இந்த வார பாதிப்புகள்',
    cases_month: 'இந்த மாத பாதிப்புகள்',
    active_outbreaks: 'செயலில் உள்ள பரவல்கள்',
    recovered_cases: 'குணமடைந்த பாதிப்புகள்',
    mortalities: 'இறப்புகள்',
    regional_alerts: 'வட்டார எச்சரிக்கை நிலைகள்',
    live_containment: 'நேரடி கட்டுப்பாட்டு செய்திகள்',
    disease_progression: 'நோய் பரவல் போக்கு',
    risk_breakdown: 'அபாய நிலை பகுப்பாய்வு',
    click_bed_info: 'படுக்கை வசதிகளை சரிபார்க்க மேலே உள்ள எந்த மாவட்டத்தையும் கிளிக் செய்யவும்.',
    
    // Case Form
    diagnose_case_title: 'தொற்று நோய் பாதிப்பு அறிக்கை',
    diagnose_case_sub: 'நிகழ்நேர வரைபடத்தில் செயலில் உள்ள கண்காணிப்பு பாதிப்புகளை சேர்க்கவும்.',
    patient_details: 'நோயாளி விவரங்கள்',
    patient_id: 'நோயாளி ஐடி (தணிக்கைக்குரியது)',
    daily_count: 'தினசரி நோயாளி எண்ணிக்கை',
    age: 'வயது',
    representative_age: 'குறிப்பிடத்தக்க வயது',
    gender_distribution: 'பாலின விநியோகம்',
    diagnosed_disease: 'கண்டறியப்பட்ட நோய் / நோய்க்கிருமி',
    severity_assessment: 'தீவிரத்தன்மை மதிப்பீடு',
    immunization_status: 'தடுப்பூசி நிலை',
    patient_vaccinated: 'நோயாளி இந்த நோய்க்கு தடுப்பூசி பெற்றுள்ளார்',
    gis_coordinates: 'ஜிஐஎஸ் ஒருங்கிணைப்பு வரைபடம்',
    auto_gps: 'தானியங்கி ஜிபிஎஸ் இருப்பிடம்',
    district: 'மாவட்டம்',
    block: 'வட்டார',
    gram_panchayat: 'கிராம பஞ்சாயத்து',
    village_ward: 'கிராமம் / வார்டு',
    diagnosis_status: 'கண்டறிதல் நிலை',
    clinical_isolation: 'மருத்துவ தனிமைப்படுத்தல் நிலை',
    hospital_name: 'மருத்துவ மையம் / மருத்துவமனை பெயர்',
    symptom_notes: 'அறிகுறி குறிப்புகள்',
    travel_history: 'பயண மற்றும் தொடர்பு வரலாறு',
    submit_report: 'நோய் பாதிப்பை சமர்ப்பிக்கவும்',
    
    // Options
    male_only: 'ஆண் மட்டும்',
    female_only: 'பெண் மட்டும்',
    other: 'இதர',
    mixed_genders: 'கலப்பு பாலினம (விநியோகிக்கப்பட்டது)',
    low_risk: 'குறைந்த அபாயம்',
    medium_alert: 'நடுத்தர எச்சரிக்கை',
    high_outbreak: 'அதி தீவிர பரவல் (அறிவிக்கவும்)',
    suspected: 'சந்தேகிக்கப்படும் பாதிப்பு',
    confirmed: 'உறுதிசெய்யப்பட்ட பாதிப்பு',
    recovered: 'குணமடைந்தார்',
    death: 'இறப்பு',
    home_quarantine: 'வீட்டு தனிமைப்படுத்தல்',
    isolation: 'PHC தனிமைப்படுத்தல் வார்டு',
    hospitalized: 'அனுமதிக்கப்பட்டவர் (படுக்கைகள்)',

    // Disease DB Headers
    disease_db_title: 'நோய் பதிவேடுகள் தரவுத்தளம்',
    disease_db_sub: 'அரசாங்கத்தால் அங்கீகரிக்கப்பட்ட நோய்க்கிருமிகள் பட்டியல் மற்றும் கட்டுப்பாட்டு வரம்புகள்.',
    configure_pathogen: 'நோய்க்கிருமியை கட்டமைக்கவும்',
    configure_pathogen_title: 'நோய்க்கிருமி கட்டுப்பாட்டு வரம்புகளை கட்டமைக்கவும்',
    pathogen_name: 'நோய்க்கிருமி பெயர்',
    category: 'வகை',
    alert_threshold: 'வாராந்திர எச்சரிக்கை வரம்பு',
    symptoms_desc: 'அறிகுறி விளக்கம்',
    treatment_checklist: 'முதலுதவி சிகிச்சை பட்டியல்',
    containment_directives: 'கட்டுப்பாட்டு மண்டல வழிகாட்டுதல்கள்',
    cancel: 'ரத்து',
    configure_registry: 'பதிவேட்டை கட்டமைக்கவும்',
    certified_text: 'மாநில சுகாதார சட்டத்தின் கீழ் சான்றளிக்கப்பட்டது',
    limit_text: 'வரம்பு',
    cases_wk: 'பாதிப்புகள்/வாரம்',
    symptoms_lbl: 'அறிகுறி',

    // Specific Disease Mock Content
    "Dengue": "டெங்கு",
    "Malaria": "மலேரியா",
    "Cholera": "காலரா",
    "Vector-borne": "பரப்பி-வழி",
    "Water-borne": "நீர்-வழி",
    "Airborne": "காற்று-வழி",
    "Direct Contact": "நேரடி தொடர்பு",
    "Focal insecticide fogging, standing water cleaning": "பூச்சிக்கொல்லி தெளித்தல், தேங்கிய நீரை சுத்தம் செய்தல்",
    "LLIN mosquito net distribution": "LLIN கொசுவலை விநியோகம்",
    "Chlorination of water sources, hygiene audits": "நீர் ஆதாரங்களை குளோரினேற்றம் செய்தல், சுகாதார தணிக்கை",
    "Paracetamol, ORS": "பாரசிட்டமால், ORS",
    "Doxycycline, ORS": "டாக்ஸிசைக்ளின், ORS",
    "High fever, respiratory complications, joint pain.": "அதிக காய்ச்சல், சுவாச சிக்கல்கள், மூட்டு வலி.",

    // AI Forecast Page
    ai_containment_forecasts: "AI கட்டுப்பாட்டு மற்றும் வெடிப்பு கணிப்புகள்",
    heuristics_engine_sub: "விண்வெளி DBSCAN கிளஸ்டர்கள் மற்றும் 7 நாள் கேஸ்லோடு வளர்ச்சி போக்குகளை கணக்கிடும் உத்திகள்.",
    predictive_growth_modeling: "முன்கணிப்பு வளர்ச்சி மாடலிங்",
    trend_calculations_sub: "செயலில் உள்ள நிலைகளுக்கான 7-நாள் போக்கு கணக்கீடுகள்",
    active_cases: "செயலில் உள்ள பாதிப்புகள்",
    forecast_7d: "7-நாள் முன்கணிப்பு",
    growth_slope: "வளர்ச்சி சரிவு",
    risk_score: "அபாய மதிப்பெண்",
    ai_action_directives: "AI நடவடிக்கை வழிகாட்டுதல்கள் - ",
    confidence_index_text: "நம்பிக்கை குறியீடு வரலாற்று ரீதியான மாவட்ட அறிக்கையிடல் அதிர்வெண்ணிலிருந்து பெறப்படுகிறது.",
    density_hotspots: "அடர்த்தி ஹாட்ஸ்பாட்கள் (DBSCAN)",
    identified_coordinates: "கடந்த 14 நாட்களில் அடையாளம் காணப்பட்ட ஒருங்கிணைப்பு கிளஸ்டர்கள்",
    no_clusters_detected: "கிளஸ்டர் வெடிப்புகள் எதுவும் கண்டறியப்படவில்லை.",
    registered_surveillance_hub: "பதிவுசெய்யப்பட்ட நோய் கண்காணிப்பு மையம் (முன்கணிப்பு உள்ளீடுகள்)",
    active_sub_registry: "மாநில நோய் பதிவேட்டின் மூலம் சமர்ப்பிக்கப்பட்ட செயலில் உள்ள நோய் பாதிப்புகள்.",
    all_years: "அனைத்து ஆண்டுகளும்",
    all_months: "அனைத்து மாதங்களும்",
    primary_pathogen: "முதன்மை நோய்க்கிருமி",
    cases_in_cluster: "கிளஸ்டரில் உள்ள பாதிப்புகள்",
    location_centroid: "இருப்பிட சென்ட்ராய்டு / ஆரம்",
    reported: "அறிவிக்கப்பட்டது",
    cluster_centroid: "கிளஸ்டர் சென்ட்ராய்டு",
    january: "ஜனவரி",
    february: "பிப்ரவரி",
    march: "மார்ச்",
    april: "ஏப்ரல்",
    may: "மே",
    june: "ஜூன்",
    july: "ஜூலை",
    august: "ஆகஸ்ட்",
    september: "செப்டம்பர்",
    october: "அக்டோபர்",
    november: "நவம்பர்",
    december: "டிசம்பர்",
    enforce_active_surveillance_prefix: "அறிவிக்கப்பட்ட பாதிப்புகளிலிருந்து 2 கிமீ சுற்றளவில் தீவிர கண்காணிப்பை அமல்படுத்தவும் -",

    // Directives
    "Eliminate standing water containers and conduct focal insecticide fogging.": "தேங்கியுள்ள தண்ணீர் பாத்திரங்களை அகற்றி, பூச்சிக்கொல்லி புகை பரப்பவும்.",
    "Distribute LLIN mosquito bed nets to households in affected blocks.": "பாதிக்கப்பட்ட பகுதிகளில் உள்ள வீடுகளுக்கு LLIN கொசுவலை விநியோகிக்கவும்.",
    "Ensure local primary health centers have adequate stocks of paracetamol and diagnostic kits.": "வட்டார ஆரம்ப சுகாதார நிலையங்களில் பாரசிட்டமால் மற்றும் கண்டறியும் கருவிகள் இருப்பதை உறுதிசெய்க.",
    "Conduct Indoor Residual Spraying (IRS) in households within a 2km radius.": "2 கிமீ சுற்றளவில் உள்ள வீடுகளில் உட்புற பூச்சிக்கொல்லி தெளிக்கவும் (IRS).",
    "Distribute LLIN mosquito nets and run community vector awareness campaigns.": "LLIN கொசுவலை விநியோகம் செய்து விழிப்புணர்வு பிரச்சாரங்களை நடத்தவும்.",
    "Stock local health facilities with ACT (Artesunate-Sulfadoxine-Pyrimethamine) therapy.": "சுகாதார நிலையங்களில் ACT சிகிச்சைக்கான மருந்துகளை சேமித்து வைக்கவும்.",
    "Establish emergency water purification points and distribute halogen tablets.": "அவசரகால குடிநீர் சுத்திகரிப்பு நிலையங்களை அமைத்து குளோரின் மாத்திரைகளை வழங்கவும்.",
    "Enforce super-chlorination of local drinking water wells and municipal reservoirs.": "குடிநீர் கிணறுகள் மற்றும் நீர்த்தேக்கங்களை சூப்பர்-குளோரினேற்றம் செய்யவும்.",
    "Deploy quarantine isolation units and stock facilities with Doxycycline and ORS.": "தனிமைப்படுத்தப்பட்ட வார்டுகளை தயார் செய்து டாக்ஸிசைக்ளின், ORS சேமிக்கவும்.",
    "Mandate face masks in public and establish immediate contact tracing for the patient ID.": "பொது இடங்களில் முகக்கவசம் கட்டாயமாக்கி, தொடர்புகளை கண்டறியவும்.",
    "Enforce localized containment quarantine zones around the active residences.": "பாதிக்கப்பட்ட வீடுகளைச் சுற்றி உள்ளூர் கட்டுப்பாட்டு மண்டலங்களை அமல்படுத்தவும்.",
    "Deploy ASHA workers for daily door-to-door temperature audits and symptom logging.": "தினசரி கணக்கெடுப்பு மற்றும் அறிகுறி பதிவுக்கு ஆஷா பணியாளர்களை நியமிக்கவும்.",
    "Enforce chlorination of local community drinking water wells.": "உள்ளூர் குடிநீர் கிணறுகளின் குளோரினேற்றத்தை அமல்படுத்தவும்.",
    "Conduct food safety sanitation audits at public food stalls and markets.": "பொது உணவு கடைகள் மற்றும் சந்தைகளில் உணவு பாதுகாப்பு தணிக்கை நடத்தவும்.",
    "Ensure local PHCs have adequate stocks of Ceftriaxone and Azithromycin.": "சுகாதார நிலையங்களில் செஃப்ட்ரியாக்சோன் மற்றும் அசித்ரோமைசின் இருப்பதை உறுதிசெய்க.",
    "Standard surveillance active. No high-risk outbreak triggers detected.": "நிலையான கண்காணிப்பு செயலில் உள்ளது. தீவிர வெடிப்பு அறிகுறிகள் ஏதுமில்லை.",
    "Monitor local ASHA health logs for abnormal spike indicators.": "ASHA சுகாதார பதிவுகளை ஏதேனும் அசாதாரண அதிகரிப்புக்கு கண்காணிக்கவும்.",
    "Enforce active surveillance within a 2km radius of positive cases.": "பாதிப்பு உள்ள பகுதியின் 2 கிமீ சுற்றளவில் தீவிர கண்காணிப்பை அமல்படுத்தவும்.",
    "Deploy ASHA workers for daily door-to-door temperature and symptom audits.": "தினசரி உடல் வெப்பநிலை மற்றும் அறிகுறி தணிக்கைகளுக்கு ஆஷா ஊழியர்களை நியமிக்கவும்.",
    "Ensure local PHCs have adequate stocks of Dengue diagnostic kits.": "ஆரம்ப சுகாதார நிலையங்களில் டெங்கு கண்டறியும் கருவிகள் இருப்பதை உறுதிசெய்க.",
    "Enforce active surveillance within a 2km radius.": "2 கிமீ சுற்றளவில் தீவிர கண்காணிப்பை அமல்படுத்தவும்.",
    "Perform targeted water chlorination and bleach distribution.": "குறிப்பிட்ட நீர் குளோரினேற்றம் மற்றும் பிளீச்சிங் பவுடர் விநியோகம் செய்யவும்.",
    "Ensure SCB medical college has stocked ORS sachets.": "எஸ்சிபி மருத்துவக் கல்லூரியில் ORS பாக்கெட்டுகள் இருப்பதை உறுதிசெய்க.",
    "ASHA workers to distribute mosquito nets in Hinjilicut.": "ஹிஞ்சிலிகட்டில் ஆஷா ஊழியர்கள் கொசுவலைகளை விநியோகிக்கவும்.",
    "Conduct indoor residual spraying.": "உட்புற பூச்சிக்கொல்லி தெளிக்கவும்.",
    "Monitor local ASHA health logs.": "உள்ளூர் ஆஷா சுகாதார பதிவுகளை கண்காணிக்கவும்.",
    patient_name_id: 'நோயாளி பெயர் & ஐடி',
    disease_pathogen: 'நோய் நோய்க்கிருமி',
    place_district: 'இடம் / மாவட்டம்',
    affected_persons_count: 'பாதிக்கப்பட்ட நபர்களின் எண்ணிக்கை',
    registration_date: 'பதிவு தேதி',
    no_registered_cases_matching: 'தேர்ந்தெடுக்கப்பட்ட வடிகட்டிகளுக்குப் பொருத்தமான பதிவுகள் இல்லை.',
    increasing: 'அதிகரிப்பு',
    stable: 'நிலையானது'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageType>('en');

  useEffect(() => {
    const storedLang = localStorage.getItem('portal_language') as LanguageType;
    if (storedLang && ['en', 'or', 'ta'].includes(storedLang)) {
      setLanguageState(storedLang);
    }
  }, []);

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem('portal_language', lang);
  };

  const t = (key: string): string => {
    return dictionary[language]?.[key] || dictionary['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
